services:
  db:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: swegram_corpus
      MYSQL_USER: swegram
      MYSQL_PASSWORD: swegram_pass
    networks:
      - swegram-network
    profiles:
      - client
      - database

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: swegram-backend:latest
    container_name: swegram-backend-fastapi
    restart: always
    platform: linux/amd64
    environment:
      CONSOLE_LOG_FILE: /var/log/console.log
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: swegram_corpus
      MYSQL_USER: swegram
      MYSQL_PASSWORD: swegram_pass
      MYSQL_HOST: db
      PRODUCTION: 1
    volumes:
      - $PWD/backend/log:/var/log
    ports:
      - "8000:8000"
    networks:
      - swegram-network
    profiles:
      - client
      - backend

  vue-nginx-proxy:
    build: frontend
    container_name: vue-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - swegram-network
    volumes:
      - $PWD/frontend/log/nginx:/var/log/nginx
    profiles:
      - client
      - frontend

networks:
  swegram-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
