version: '3.1'

services:

  db:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: swegram_corpus
      MYSQL_USER: swegram
      MYSQL_PASSWORD: swegram_pass
    networks:
      - swegram-network
    profiles:
      - client
      - frontend

  backend:
    image: rex0046/swegram-backend:1.0.4  # Image needs to be built with network
    depends_on:
      - db
    container_name: swegram-backend-fastapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: swegram_corpus
      MYSQL_USER: swegram
      MYSQL_PASSWORD: swegram_pass
      MYSQL_HOST: 172.18.0.1
      PRODUCTION: 1
    ports:
      - "8000:8000"
    entrypoint: >
      bash -c "cd /root && sleep 30 && python3 app_run.py"
    networks:
      - swegram-network
    profiles:
      - client
      - backend

  vue-nginx-proxy:
    build: frontend
    depends_on:
      - db
      - backend
    container_name: vue-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - swegram-network
    profiles:
      - client

networks:
  swegram-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
