1.1	1	Återupptagande	_	återupptagande	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.1	2	av	_	av	ADP	PP	_	_	_	_	_	_
1.1	3	sessionen	_	session	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.1	4	Jag	_	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.1	5	förklarar	_	förklara	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.1	6	Europaparlamentets	_	europaparlament	NOUN	NN	Case=Gen|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|GEN	_	_	_	_
1.1	7	session	_	session	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.1	8	återupptagen	_	återupptagen	ADJ	PC	Case=Nom|Definite=Ind|Gender=Com|Number=Sing|Tense=Past|VerbForm=Part	PRF|UTR|SIN|IND|NOM	_	_	_	_
1.1	9	efter	_	efter	ADP	PP	_	_	_	_	_	_
1.1	10	avbrottet	_	avbrott	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.1	11	den	_	den	DET	DT	Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF	_	_	_	_
1.1	12	17	_	17	NUM	RG	Case=Nom	NOM	_	_	_	_
1.1	13	december	_	december	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.1	14	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.2	1	Jag	_	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	2	vill	_	vilja	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.2	3	på	_	på	ADP	PP	_	_	_	_	_	_
1.2	4	nytt	_	nytt	ADV	AB	Degree=Pos	POS	_	_	_	_
1.2	5	önska	_	önska	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.2	6	er	_	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.2	7	ett	_	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.2	8	gott	_	god	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing	POS|NEU|SIN|IND|NOM	_	_	_	_
1.2	9	nytt	_	ny	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing	POS|NEU|SIN|IND|NOM	_	_	_	_
1.2	10	år	_	år	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.2	11	och	_	och	CCONJ	KN	_	_	_	_	_	_
1.2	12	jag	_	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	13	hoppas	_	hoppas	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Pass	PRS|SFO	_	_	_	_
1.2	14	att	_	att	SCONJ	SN	_	_	_	_	_	_
1.2	15	ni	_	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	16	haft	_	ha	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.2	17	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.2	18	trevlig	_	trevlig	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.2	19	semester	_	semester	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.2	20	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.3	1	Som	_	som	CCONJ	KN	_	_	_	_	_	_
1.3	2	ni	_	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.3	3	kunnat	_	kunna	AUX	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.3	4	konstatera	_	konstatera	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.3	5	ägde	_	äga	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.3	6	"	_	"	PUNCT	PAD	_	_	_	_	_	_
1.3	7	den	_	den	DET	DT	Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF	_	_	_	_
1.3	8	stora	_	stor	ADJ	JJ	Case=Nom|Definite=Def|Degree=Pos|Number=Sing	POS|UTR/NEU|SIN|DEF|NOM	_	_	_	_
1.3	9	år	_	år	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.3	10	2000	_	2000	NUM	RG	Case=Nom	NOM	_	_	_	_
1.3	11	-	_	-	PUNCT	MID	_	_	_	_	_	_
1.3	12	buggen	_	bugg	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.3	13	"	_	"	PUNCT	PAD	_	_	_	_	_	_
1.3	14	aldrig	_	aldrig	ADV	AB	Polarity=Neg	_	_	_	_	_
1.3	15	rum	_	rum	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.3	16	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.4	1	Däremot	_	däremot	ADV	AB	_	_	_	_	_	_
1.4	2	har	_	ha	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.4	3	invånarna	_	invånare	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|NOM	_	_	_	_
1.4	4	i	_	i	ADP	PP	_	_	_	_	_	_
1.4	5	ett	_	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.4	6	antal	_	antal	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.4	7	av	_	av	ADP	PP	_	_	_	_	_	_
1.4	8	våra	_	vår	DET	PS	Definite=Def|Number=Plur|Poss=Yes	UTR/NEU|PLU|DEF	_	_	_	_
1.4	9	medlemsländer	_	medlemsland	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.4	10	drabbats	_	drabba	VERB	VB	VerbForm=Sup|Voice=Pass	SUP|SFO	_	_	_	_
1.4	11	av	_	av	ADP	PP	_	_	_	_	_	_
1.4	12	naturkatastrofer	_	naturkatastrof	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.4	13	som	_	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.4	14	verkligen	_	verkligen	ADV	AB	_	_	_	_	_	_
1.4	15	varit	_	vara	AUX	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.4	16	förskräckliga	_	förskräcklig	ADJ	JJ	Case=Nom|Degree=Pos|Number=Plur	POS|UTR/NEU|PLU|IND/DEF|NOM	_	_	_	_
1.4	17	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.5	1	Ni	_	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.5	2	har	_	ha	AUX	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.5	3	begärt	_	begära	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.5	4	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.5	5	debatt	_	debatt	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.5	6	i	_	i	ADP	PP	_	_	_	_	_	_
1.5	7	ämnet	_	ämne	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.5	8	under	_	under	ADP	PP	_	_	_	_	_	_
1.5	9	sammanträdesperiodens	_	sammanträdesperiod	NOUN	NN	Case=Gen|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|GEN	_	_	_	_
1.5	10	kommande	_	kommande	ADJ	PC	Case=Nom|Mood=Ind|Tense=Pres|VerbForm=Fin	PRS|UTR/NEU|SIN/PLU|IND/DEF|NOM	_	_	_	_
1.5	11	dagar	_	dag	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.5	12	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.6	1	Till	_	till	ADP	PP	_	_	_	_	_	_
1.6	2	dess	_	dess	ADV	AB	_	_	_	_	_	_
1.6	3	vill	_	vilja	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.6	4	jag	_	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.6	5	att	_	att	SCONJ	SN	_	_	_	_	_	_
1.6	6	vi	_	vi	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.6	7	,	_	,	PUNCT	MID	_	_	_	_	_	_
1.6	8	som	_	som	CCONJ	KN	_	_	_	_	_	_
1.6	9	ett	_	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.6	10	antal	_	antal	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.6	11	kolleger	_	kollega	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.6	12	begärt	_	begära	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.6	13	,	_	,	PUNCT	MID	_	_	_	_	_	_
1.6	14	håller	_	hålla	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.6	15	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.6	16	tyst	_	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.6	17	minut	_	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.6	18	för	_	för	ADP	PP	_	_	_	_	_	_
1.6	19	offren	_	offer	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Plur	NEU|PLU|DEF|NOM	_	_	_	_
1.6	20	för	_	för	ADP	PP	_	_	_	_	_	_
1.6	21	bl.a.	_	bland_annat	ADV	AB	Abbr=Yes	AN	_	_	_	_
1.6	22	stormarna	_	storm	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|NOM	_	_	_	_
1.6	23	i	_	i	ADP	PP	_	_	_	_	_	_
1.6	24	de	_	den	DET	DT	Definite=Def|Number=Plur	UTR/NEU|PLU|DEF	_	_	_	_
1.6	25	länder	_	land	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.6	26	i	_	i	ADP	PP	_	_	_	_	_	_
1.6	27	Europeiska	_	europeisk	ADJ	JJ	Case=Nom|Definite=Def|Degree=Pos|Number=Sing	POS|UTR/NEU|SIN|DEF|NOM	_	_	_	_
1.6	28	unionen	_	union	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.6	29	som	_	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.6	30	drabbats	_	drabba	VERB	VB	VerbForm=Sup|Voice=Pass	SUP|SFO	_	_	_	_
1.6	31	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.7	1	Jag	_	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.7	2	ber	_	be	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.7	3	er	_	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.7	4	resa	_	resa	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.7	5	er	_	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.7	6	för	_	för	ADP	PP	_	_	_	_	_	_
1.7	7	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.7	8	tyst	_	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.7	9	minut	_	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	10	.	_	.	PUNCT	MAD	_	_	_	_	_	_
1.7	11	(	_	(	PUNCT	PAD	_	_	_	_	_	_
1.7	12	Parlamentet	_	parlament	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.7	13	höll	_	hålla	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.7	14	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.7	15	tyst	_	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.7	16	minut	_	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	17	.	_	.	PUNCT	MAD	_	_	_	_	_	_
1.7	18	)	_	)	PUNCT	PAD	_	_	_	_	_	_
1.7	19	Fru	_	fru	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	20	talman	_	talman	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	21	!	_	!	PUNCT	MAD	_	_	_	_	_	_

1.8	1	Det	_	det	PRON	PN	Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|SUB/OBJ	_	_	_	_
1.8	2	gäller	_	gälla	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.8	3	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.8	4	ordningsfråga	_	ordningsfråga	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.8	5	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.9	1	Ni	_	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.9	2	känner	_	känna	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.9	3	till	_	till	ADP	PL	_	_	_	_	_	_
1.9	4	från	_	från	ADP	PP	_	_	_	_	_	_
1.9	5	media	_	media	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.9	6	att	_	att	SCONJ	SN	_	_	_	_	_	_
1.9	7	det	_	det	PRON	PN	Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|SUB/OBJ	_	_	_	_
1.9	8	skett	_	ske	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.9	9	en	_	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.9	10	rad	_	rad	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.9	11	bombexplosioner	_	bombexplosion	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.9	12	och	_	och	CCONJ	KN	_	_	_	_	_	_
1.9	13	mord	_	mord	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.9	14	i	_	i	ADP	PP	_	_	_	_	_	_
1.9	15	Sri	_	Sri	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.9	16	Lanka	_	Lanka	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.9	17	.	_	.	PUNCT	MAD	_	_	_	_	_	_

1.10	1	En	_	en	PRON	PN	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|SUB/OBJ	_	_	_	_
1.10	2	av	_	av	ADP	PP	_	_	_	_	_	_
1.10	3	de	_	den	DET	DT	Definite=Def|Number=Plur	UTR/NEU|PLU|DEF	_	_	_	_
1.10	4	personer	_	person	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.10	5	som	_	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.10	6	mycket	_	mycket	ADV	AB	Degree=Pos	POS	_	_	_	_
1.10	7	nyligen	_	nyligen	ADV	AB	_	_	_	_	_	_
1.10	8	mördades	_	mörda	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Pass	PRT|SFO	_	_	_	_
1.10	9	i	_	i	ADP	PP	_	_	_	_	_	_
1.10	10	Sri	_	Sri	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	11	Lanka	_	Lanka	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	12	var	_	vara	AUX	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.10	13	Kumar	_	Kumar	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	14	Ponnambalam	_	Ponnambalam	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	15	,	_	,	PUNCT	MID	_	_	_	_	_	_
1.10	16	som	_	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.10	17	besökte	_	besöka	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.10	18	Europaparlamentet	_	europaparlament	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.10	19	för	_	för	ADP	PP	_	_	_	_	_	_
1.10	20	bara	_	bara	ADV	AB	_	_	_	_	_	_
1.10	21	några	_	någon	DET	DT	Definite=Ind|Number=Plur	UTR/NEU|PLU|IND	_	_	_	_
1.10	22	månader	_	månad	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.10	23	sedan	_	sedan	ADV	AB	_	_	_	_	_	_
1.10	24	.	_	.	PUNCT	MAD	_	_	_	_	_	_

