1.1	1	Återupptagande	Återupptagande	återupptagande	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.1	2	av	av	av	ADP	PP	_	_	_	_	_	_
1.1	3	sessionen	sessionen	session	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.1	4	Jag	Jag	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.1	5	förklarar	förklarar	förklara	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.1	6	Europaparlamentets	Europaparlamentets	europaparlament	NOUN	NN	Case=Gen|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|GEN	_	_	_	_
1.1	7	session	session	session	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.1	8	återupptagen	återupptagen	återupptagen	ADJ	PC	Case=Nom|Definite=Ind|Gender=Com|Number=Sing|Tense=Past|VerbForm=Part	PRF|UTR|SIN|IND|NOM	_	_	_	_
1.1	9	efter	efter	efter	ADP	PP	_	_	_	_	_	_
1.1	10	avbrottet	avbrottet	avbrott	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.1	11	den	den	den	DET	DT	Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF	_	_	_	_
1.1	12	17	17	17	NUM	RG	Case=Nom	NOM	_	_	_	_
1.1	13	december	december	december	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.1	14	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.2	1	Jag	Jag	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	2	vill	vill	vilja	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.2	3	på	på	på	ADP	PP	_	_	_	_	_	_
1.2	4	nytt	nytt	nytt	ADV	AB	Degree=Pos	POS	_	_	_	_
1.2	5	önska	önska	önska	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.2	6	er	er	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.2	7	ett	ett	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.2	8	gott	gott	god	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing	POS|NEU|SIN|IND|NOM	_	_	_	_
1.2	9	nytt	nytt	ny	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Neut|Number=Sing	POS|NEU|SIN|IND|NOM	_	_	_	_
1.2	10	år	år	år	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.2	11	och	och	och	CCONJ	KN	_	_	_	_	_	_
1.2	12	jag	jag	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	13	hoppas	hoppas	hoppas	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Pass	PRS|SFO	_	_	_	_
1.2	14	att	att	att	SCONJ	SN	_	_	_	_	_	_
1.2	15	ni	ni	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.2	16	haft	haft	ha	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.2	17	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.2	18	trevlig	trevlig	trevlig	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.2	19	semester	semester	semester	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.2	20	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.3	1	Som	Som	som	CCONJ	KN	_	_	_	_	_	_
1.3	2	ni	ni	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.3	3	kunnat	kunnat	kunna	AUX	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.3	4	konstatera	konstatera	konstatera	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.3	5	ägde	ägde	äga	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.3	6	"	"	"	PUNCT	PAD	_	_	_	_	_	_
1.3	7	den	den	den	DET	DT	Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF	_	_	_	_
1.3	8	stora	stora	stor	ADJ	JJ	Case=Nom|Definite=Def|Degree=Pos|Number=Sing	POS|UTR/NEU|SIN|DEF|NOM	_	_	_	_
1.3	9	år	år	år	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.3	10	2000	2000	2000	NUM	RG	Case=Nom	NOM	_	_	_	_
1.3	11	-	-	-	PUNCT	MID	_	_	_	_	_	_
1.3	12	buggen	buggen	bugg	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.3	13	"	"	"	PUNCT	PAD	_	_	_	_	_	_
1.3	14	aldrig	aldrig	aldrig	ADV	AB	Polarity=Neg	_	_	_	_	_
1.3	15	rum	rum	rum	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.3	16	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.4	1	Däremot	Däremot	däremot	ADV	AB	_	_	_	_	_	_
1.4	2	har	har	ha	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.4	3	invånarna	invånarna	invånare	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|NOM	_	_	_	_
1.4	4	i	i	i	ADP	PP	_	_	_	_	_	_
1.4	5	ett	ett	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.4	6	antal	antal	antal	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.4	7	av	av	av	ADP	PP	_	_	_	_	_	_
1.4	8	våra	våra	vår	DET	PS	Definite=Def|Number=Plur|Poss=Yes	UTR/NEU|PLU|DEF	_	_	_	_
1.4	9	medlemsländer	medlemsländer	medlemsland	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.4	10	drabbats	drabbats	drabba	VERB	VB	VerbForm=Sup|Voice=Pass	SUP|SFO	_	_	_	_
1.4	11	av	av	av	ADP	PP	_	_	_	_	_	_
1.4	12	naturkatastrofer	naturkatastrofer	naturkatastrof	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.4	13	som	som	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.4	14	verkligen	verkligen	verkligen	ADV	AB	_	_	_	_	_	_
1.4	15	varit	varit	vara	AUX	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.4	16	förskräckliga	förskräckliga	förskräcklig	ADJ	JJ	Case=Nom|Degree=Pos|Number=Plur	POS|UTR/NEU|PLU|IND/DEF|NOM	_	_	_	_
1.4	17	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.5	1	Ni	Ni	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.5	2	har	har	ha	AUX	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.5	3	begärt	begärt	begära	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.5	4	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.5	5	debatt	debatt	debatt	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.5	6	i	i	i	ADP	PP	_	_	_	_	_	_
1.5	7	ämnet	ämnet	ämne	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.5	8	under	under	under	ADP	PP	_	_	_	_	_	_
1.5	9	sammanträdesperiodens	sammanträdesperiodens	sammanträdesperiod	NOUN	NN	Case=Gen|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|GEN	_	_	_	_
1.5	10	kommande	kommande	kommande	ADJ	PC	Case=Nom|Mood=Ind|Tense=Pres|VerbForm=Fin	PRS|UTR/NEU|SIN/PLU|IND/DEF|NOM	_	_	_	_
1.5	11	dagar	dagar	dag	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.5	12	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.6	1	Till	Till	till	ADP	PP	_	_	_	_	_	_
1.6	2	dess	dess	dess	ADV	AB	_	_	_	_	_	_
1.6	3	vill	vill	vilja	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.6	4	jag	jag	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.6	5	att	att	att	SCONJ	SN	_	_	_	_	_	_
1.6	6	vi	vi	vi	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.6	7	,	,	,	PUNCT	MID	_	_	_	_	_	_
1.6	8	som	som	som	CCONJ	KN	_	_	_	_	_	_
1.6	9	ett	ett	en	DET	DT	Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND	_	_	_	_
1.6	10	antal	antal	antal	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Sing	NEU|SIN|IND|NOM	_	_	_	_
1.6	11	kolleger	kolleger	kollega	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.6	12	begärt	begärt	begära	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.6	13	,	,	,	PUNCT	MID	_	_	_	_	_	_
1.6	14	håller	håller	hålla	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.6	15	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.6	16	tyst	tyst	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.6	17	minut	minut	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.6	18	för	för	för	ADP	PP	_	_	_	_	_	_
1.6	19	offren	offren	offer	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Plur	NEU|PLU|DEF|NOM	_	_	_	_
1.6	20	för	för	för	ADP	PP	_	_	_	_	_	_
1.6	21	bl.a.	bl.a.	bland_annat	ADV	AB	Abbr=Yes	AN	_	_	_	_
1.6	22	stormarna	stormarna	storm	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|NOM	_	_	_	_
1.6	23	i	i	i	ADP	PP	_	_	_	_	_	_
1.6	24	de	de	den	DET	DT	Definite=Def|Number=Plur	UTR/NEU|PLU|DEF	_	_	_	_
1.6	25	länder	länder	land	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.6	26	i	i	i	ADP	PP	_	_	_	_	_	_
1.6	27	Europeiska	Europeiska	europeisk	ADJ	JJ	Case=Nom|Definite=Def|Degree=Pos|Number=Sing	POS|UTR/NEU|SIN|DEF|NOM	_	_	_	_
1.6	28	unionen	unionen	union	NOUN	NN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|NOM	_	_	_	_
1.6	29	som	som	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.6	30	drabbats	drabbats	drabba	VERB	VB	VerbForm=Sup|Voice=Pass	SUP|SFO	_	_	_	_
1.6	31	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.7	1	Jag	Jag	jag	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|SUB	_	_	_	_
1.7	2	ber	ber	be	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.7	3	er	er	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.7	4	resa	resa	resa	VERB	VB	VerbForm=Inf|Voice=Act	INF|AKT	_	_	_	_
1.7	5	er	er	ni	PRON	PN	Case=Acc|Definite=Def|Gender=Com|Number=Sing	UTR|SIN|DEF|OBJ	_	_	_	_
1.7	6	för	för	för	ADP	PP	_	_	_	_	_	_
1.7	7	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.7	8	tyst	tyst	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.7	9	minut	minut	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	10	.	.	.	PUNCT	MAD	_	_	_	_	_	_
1.7	11	(	(	(	PUNCT	PAD	_	_	_	_	_	_
1.7	12	Parlamentet	Parlamentet	parlament	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.7	13	höll	höll	hålla	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.7	14	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.7	15	tyst	tyst	tyst	ADJ	JJ	Case=Nom|Definite=Ind|Degree=Pos|Gender=Com|Number=Sing	POS|UTR|SIN|IND|NOM	_	_	_	_
1.7	16	minut	minut	minut	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	17	.	.	.	PUNCT	MAD	_	_	_	_	_	_
1.7	18	)	)	)	PUNCT	PAD	_	_	_	_	_	_
1.7	19	Fru	Fru	fru	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	20	talman	talman	talman	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.7	21	!	!	!	PUNCT	MAD	_	_	_	_	_	_

1.8	1	Det	Det	det	PRON	PN	Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|SUB/OBJ	_	_	_	_
1.8	2	gäller	gäller	gälla	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.8	3	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.8	4	ordningsfråga	ordningsfråga	ordningsfråga	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.8	5	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.9	1	Ni	Ni	ni	PRON	PN	Case=Nom|Definite=Def|Gender=Com|Number=Plur	UTR|PLU|DEF|SUB	_	_	_	_
1.9	2	känner	känner	känna	VERB	VB	Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act	PRS|AKT	_	_	_	_
1.9	3	till	till	till	ADP	PL	_	_	_	_	_	_
1.9	4	från	från	från	ADP	PP	_	_	_	_	_	_
1.9	5	media	media	media	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.9	6	att	att	att	SCONJ	SN	_	_	_	_	_	_
1.9	7	det	det	det	PRON	PN	Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|SUB/OBJ	_	_	_	_
1.9	8	skett	skett	ske	VERB	VB	VerbForm=Sup|Voice=Act	SUP|AKT	_	_	_	_
1.9	9	en	en	en	DET	DT	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND	_	_	_	_
1.9	10	rad	rad	rad	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|NOM	_	_	_	_
1.9	11	bombexplosioner	bombexplosioner	bombexplosion	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.9	12	och	och	och	CCONJ	KN	_	_	_	_	_	_
1.9	13	mord	mord	mord	NOUN	NN	Case=Nom|Definite=Ind|Gender=Neut|Number=Plur	NEU|PLU|IND|NOM	_	_	_	_
1.9	14	i	i	i	ADP	PP	_	_	_	_	_	_
1.9	15	Sri	Sri	Sri	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.9	16	Lanka	Lanka	Lanka	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.9	17	.	.	.	PUNCT	MAD	_	_	_	_	_	_

1.10	1	En	En	en	PRON	PN	Definite=Ind|Gender=Com|Number=Sing	UTR|SIN|IND|SUB/OBJ	_	_	_	_
1.10	2	av	av	av	ADP	PP	_	_	_	_	_	_
1.10	3	de	de	den	DET	DT	Definite=Def|Number=Plur	UTR/NEU|PLU|DEF	_	_	_	_
1.10	4	personer	personer	person	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.10	5	som	som	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.10	6	mycket	mycket	mycket	ADV	AB	Degree=Pos	POS	_	_	_	_
1.10	7	nyligen	nyligen	nyligen	ADV	AB	_	_	_	_	_	_
1.10	8	mördades	mördades	mörda	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Pass	PRT|SFO	_	_	_	_
1.10	9	i	i	i	ADP	PP	_	_	_	_	_	_
1.10	10	Sri	Sri	Sri	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	11	Lanka	Lanka	Lanka	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	12	var	var	vara	AUX	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.10	13	Kumar	Kumar	Kumar	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	14	Ponnambalam	Ponnambalam	Ponnambalam	PROPN	PM	Case=Nom	NOM	_	_	_	_
1.10	15	,	,	,	PUNCT	MID	_	_	_	_	_	_
1.10	16	som	som	som	PRON	HP	PronType=Int,Rel	-|-|-	_	_	_	_
1.10	17	besökte	besökte	besöka	VERB	VB	Mood=Ind|Tense=Past|VerbForm=Fin|Voice=Act	PRT|AKT	_	_	_	_
1.10	18	Europaparlamentet	Europaparlamentet	europaparlament	NOUN	NN	Case=Nom|Definite=Def|Gender=Neut|Number=Sing	NEU|SIN|DEF|NOM	_	_	_	_
1.10	19	för	för	för	ADP	PP	_	_	_	_	_	_
1.10	20	bara	bara	bara	ADV	AB	_	_	_	_	_	_
1.10	21	några	några	någon	DET	DT	Definite=Ind|Number=Plur	UTR/NEU|PLU|IND	_	_	_	_
1.10	22	månader	månader	månad	NOUN	NN	Case=Nom|Definite=Ind|Gender=Com|Number=Plur	UTR|PLU|IND|NOM	_	_	_	_
1.10	23	sedan	sedan	sedan	ADV	AB	_	_	_	_	_	_
1.10	24	.	.	.	PUNCT	MAD	_	_	_	_	_	_

