# Generated by Django 3.1.2 on 2021-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swegram_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstats',
            name='number_of_paragraphs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textstats',
            name='number_of_sentences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
