# Generated by Django 3.1.2 on 2021-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swegram_main', '0002_auto_20211209_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textstats',
            name='text_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
